/*
 * Copyright (c) 2017 ARWANTECH CREATIVE TEAM
 *
 * Anda diperkenankan mengedit isi dari source code ini
 * asalkan tetap menyertakan copyright ini.
 *
 * File ini dibuat menggunakan :
 * Editor     : NetBeans IDE 8.0.2
 * NoteBook   : ASUS Notebook K42F
 * OS         : Windows 10 Pro 64bit
 * Compiler   : JDK 8 update 18
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 *      http://www.apache.org/licenses/LICENSE-2.0
 */
package com.arwantech.docjavaui.form;

import com.arwantech.javaui.efek.TransitionTextfield;
import com.arwantech.javaui.utils.Utility;
import javax.swing.text.JTextComponent;

/**
 *
 * @author AriMaulana99
 */
public class FormInput extends javax.swing.JPanel {
    private AppMainFrm main = null;

    public AppMainFrm getMain() {
        return main;
    }

    public void setMain(AppMainFrm main) {
        this.main = main;
    }
    
    
    /**
     * Creates new form DataTables
     */
    public FormInput() {
        initComponents();
        initUI();
    }
    
    private void initUI() {
        setInputUI(tfInput1_1);
        Utility.setInputUI(tfInput1_1, lblInput1_1);
        setInputUI(tfInput1_2);
        Utility.setInputUI(tfInput1_2, lblInput1_2);
        setInputUI(tfInput1_3);
        Utility.setInputUI(tfInput1_3, lblInput1_3);
        setInputUI(tfInput1_4);
        Utility.setInputUI(tfInput1_4, lblInput1_4);
        setInputUI(tfInput1_5);
        Utility.setInputUI(tfInput1_5, lblInput1_5);
        
        setInputUI1(tfInput2_1);
        Utility.setInputUI(tfInput2_1, lblInput2_1);
        setInputUI1(tfInput2_2);
        Utility.setInputUI(tfInput2_2, lblInput2_2);
        setInputUI1(tfInput2_3);
        Utility.setInputUI(tfInput2_3, lblInput2_3);
        setInputUI1(tfInput2_4);
        Utility.setInputUI(tfInput2_4, lblInput2_4);
        setInputUI1(tfInput2_5);
        Utility.setInputUI(tfInput2_5, lblInput2_5);
    }
    
    private void setInputUI(JTextComponent textField) {
        TransitionTextfield tt = new TransitionTextfield(textField);
        tt.setColorType(3);
        tt.setSpeed(50);
        tt.initTransitionMaterialUI();
    }
    
    private void setInputUI1(JTextComponent textField) {
        TransitionTextfield tt = new TransitionTextfield(textField);
        tt.setColorType(3);
        tt.setSpeed(50);
        tt.initTransitionKotak();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblInput1_1 = new javax.swing.JLabel();
        tfInput1_1 = new javax.swing.JTextField();
        lblInput1_2 = new javax.swing.JLabel();
        tfInput1_2 = new javax.swing.JTextField();
        lblInput1_3 = new javax.swing.JLabel();
        tfInput1_3 = new javax.swing.JTextField();
        lblInput1_4 = new javax.swing.JLabel();
        tfInput1_4 = new javax.swing.JTextField();
        lblInput1_5 = new javax.swing.JLabel();
        tfInput1_5 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblInput2_1 = new javax.swing.JLabel();
        tfInput2_1 = new javax.swing.JTextField();
        lblInput2_2 = new javax.swing.JLabel();
        tfInput2_2 = new javax.swing.JTextField();
        lblInput2_3 = new javax.swing.JLabel();
        tfInput2_3 = new javax.swing.JTextField();
        lblInput2_4 = new javax.swing.JLabel();
        tfInput2_4 = new javax.swing.JTextField();
        lblInput2_5 = new javax.swing.JLabel();
        tfInput2_5 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 191, 191), 1, true));

        jPanel12.setBackground(new java.awt.Color(56, 59, 68));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Form Input");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 191, 191), 1, true));

        jPanel14.setBackground(new java.awt.Color(242, 242, 242));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Input1");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInput1_1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput1_1.setForeground(new java.awt.Color(153, 153, 153));
        lblInput1_1.setText("Masukan Input1");
        lblInput1_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(lblInput1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, 20));

        tfInput1_1.setBackground(new java.awt.Color(255, 255, 255));
        tfInput1_1.setForeground(new java.awt.Color(102, 102, 102));
        tfInput1_1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(191, 191, 191)));
        tfInput1_1.setMinimumSize(new java.awt.Dimension(2, 30));
        tfInput1_1.setOpaque(false);
        tfInput1_1.setPreferredSize(new java.awt.Dimension(80, 30));
        tfInput1_1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfInput1_1CaretUpdate(evt);
            }
        });
        jPanel1.add(tfInput1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 380, 40));

        lblInput1_2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput1_2.setForeground(new java.awt.Color(153, 153, 153));
        lblInput1_2.setText("Masukan Input2");
        lblInput1_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(lblInput1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 130, 20));

        tfInput1_2.setBackground(new java.awt.Color(255, 255, 255));
        tfInput1_2.setForeground(new java.awt.Color(102, 102, 102));
        tfInput1_2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(191, 191, 191)));
        tfInput1_2.setMinimumSize(new java.awt.Dimension(2, 30));
        tfInput1_2.setOpaque(false);
        tfInput1_2.setPreferredSize(new java.awt.Dimension(80, 30));
        tfInput1_2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfInput1_2CaretUpdate(evt);
            }
        });
        jPanel1.add(tfInput1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 380, 40));

        lblInput1_3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput1_3.setForeground(new java.awt.Color(153, 153, 153));
        lblInput1_3.setText("Masukan Input3");
        lblInput1_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(lblInput1_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 130, 20));

        tfInput1_3.setBackground(new java.awt.Color(255, 255, 255));
        tfInput1_3.setForeground(new java.awt.Color(102, 102, 102));
        tfInput1_3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(191, 191, 191)));
        tfInput1_3.setMinimumSize(new java.awt.Dimension(2, 30));
        tfInput1_3.setOpaque(false);
        tfInput1_3.setPreferredSize(new java.awt.Dimension(80, 30));
        tfInput1_3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfInput1_3CaretUpdate(evt);
            }
        });
        jPanel1.add(tfInput1_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 380, 40));

        lblInput1_4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput1_4.setForeground(new java.awt.Color(153, 153, 153));
        lblInput1_4.setText("Masukan Input4");
        lblInput1_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(lblInput1_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 130, 20));

        tfInput1_4.setBackground(new java.awt.Color(255, 255, 255));
        tfInput1_4.setForeground(new java.awt.Color(102, 102, 102));
        tfInput1_4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(191, 191, 191)));
        tfInput1_4.setMinimumSize(new java.awt.Dimension(2, 30));
        tfInput1_4.setOpaque(false);
        tfInput1_4.setPreferredSize(new java.awt.Dimension(80, 30));
        tfInput1_4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfInput1_4CaretUpdate(evt);
            }
        });
        jPanel1.add(tfInput1_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 390, 40));

        lblInput1_5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput1_5.setForeground(new java.awt.Color(153, 153, 153));
        lblInput1_5.setText("Masukan Input5");
        lblInput1_5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(lblInput1_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 140, 20));

        tfInput1_5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tfInput1_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 390, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Reset Input");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPreferredSize(new java.awt.Dimension(77, 35));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 100, -1));

        jButton4.setBackground(new java.awt.Color(0, 102, 204));
        jButton4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Proses");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setPreferredSize(new java.awt.Dimension(77, 35));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 90, -1));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 191, 191), 1, true));

        jPanel16.setBackground(new java.awt.Color(242, 242, 242));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Input2");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInput2_1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_1.setForeground(new java.awt.Color(153, 153, 153));
        lblInput2_1.setText("Masukan Input1");
        lblInput2_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 20));

        tfInput2_1.setBackground(new java.awt.Color(255, 255, 255));
        tfInput2_1.setForeground(new java.awt.Color(102, 102, 102));
        tfInput2_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(191, 191, 191)));
        tfInput2_1.setMinimumSize(new java.awt.Dimension(2, 30));
        tfInput2_1.setOpaque(false);
        tfInput2_1.setPreferredSize(new java.awt.Dimension(80, 30));
        tfInput2_1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfInput2_1CaretUpdate(evt);
            }
        });
        jPanel2.add(tfInput2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 430, 40));

        lblInput2_2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_2.setForeground(new java.awt.Color(153, 153, 153));
        lblInput2_2.setText("Masukan Input2");
        lblInput2_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 150, 20));

        tfInput2_2.setBackground(new java.awt.Color(255, 255, 255));
        tfInput2_2.setForeground(new java.awt.Color(102, 102, 102));
        tfInput2_2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(191, 191, 191)));
        tfInput2_2.setMinimumSize(new java.awt.Dimension(2, 30));
        tfInput2_2.setOpaque(false);
        tfInput2_2.setPreferredSize(new java.awt.Dimension(80, 30));
        tfInput2_2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfInput2_2CaretUpdate(evt);
            }
        });
        jPanel2.add(tfInput2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 430, 40));

        lblInput2_3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_3.setForeground(new java.awt.Color(153, 153, 153));
        lblInput2_3.setText("Masukan Input3");
        lblInput2_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 150, 20));

        tfInput2_3.setBackground(new java.awt.Color(255, 255, 255));
        tfInput2_3.setForeground(new java.awt.Color(102, 102, 102));
        tfInput2_3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(191, 191, 191)));
        tfInput2_3.setMinimumSize(new java.awt.Dimension(2, 30));
        tfInput2_3.setOpaque(false);
        tfInput2_3.setPreferredSize(new java.awt.Dimension(80, 30));
        tfInput2_3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfInput2_3CaretUpdate(evt);
            }
        });
        jPanel2.add(tfInput2_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 430, 40));

        lblInput2_4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_4.setForeground(new java.awt.Color(153, 153, 153));
        lblInput2_4.setText("Masukan Input4");
        lblInput2_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 150, 20));

        tfInput2_4.setBackground(new java.awt.Color(255, 255, 255));
        tfInput2_4.setForeground(new java.awt.Color(102, 102, 102));
        tfInput2_4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(191, 191, 191)));
        tfInput2_4.setMinimumSize(new java.awt.Dimension(2, 30));
        tfInput2_4.setOpaque(false);
        tfInput2_4.setPreferredSize(new java.awt.Dimension(80, 30));
        tfInput2_4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfInput2_4CaretUpdate(evt);
            }
        });
        jPanel2.add(tfInput2_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 430, 40));

        lblInput2_5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_5.setForeground(new java.awt.Color(153, 153, 153));
        lblInput2_5.setText("Masukan Input5");
        lblInput2_5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 180, 20));

        tfInput2_5.setBackground(new java.awt.Color(255, 255, 255));
        tfInput2_5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(191, 191, 191)));
        jPanel2.add(tfInput2_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 430, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Reset Input");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(77, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 100, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Proses");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(77, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 90, -1));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        add(jPanel11, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tfInput1_2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfInput1_2CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInput1_2CaretUpdate

    private void tfInput1_3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfInput1_3CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInput1_3CaretUpdate

    private void tfInput1_4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfInput1_4CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInput1_4CaretUpdate

    private void tfInput1_1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfInput1_1CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInput1_1CaretUpdate

    private void tfInput2_1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfInput2_1CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInput2_1CaretUpdate

    private void tfInput2_2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfInput2_2CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInput2_2CaretUpdate

    private void tfInput2_3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfInput2_3CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInput2_3CaretUpdate

    private void tfInput2_4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfInput2_4CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInput2_4CaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Utility.clearALLTxt(tfInput2_1, tfInput2_2, tfInput2_3, tfInput2_4, tfInput2_5);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Utility.confirmDialog(main, jButton1, "Apakah anda yakin akan melanjutkan transaksi ?");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Utility.clearALLTxt(tfInput1_1, tfInput1_2, tfInput1_3, tfInput1_4, tfInput1_5);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Utility.messageBox(main, jButton1, "Transaksi anda berhasil di lakukan, silahkan cek kembali");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblInput1_1;
    private javax.swing.JLabel lblInput1_2;
    private javax.swing.JLabel lblInput1_3;
    private javax.swing.JLabel lblInput1_4;
    private javax.swing.JLabel lblInput1_5;
    private javax.swing.JLabel lblInput2_1;
    private javax.swing.JLabel lblInput2_2;
    private javax.swing.JLabel lblInput2_3;
    private javax.swing.JLabel lblInput2_4;
    private javax.swing.JLabel lblInput2_5;
    private javax.swing.JTextField tfInput1_1;
    private javax.swing.JTextField tfInput1_2;
    private javax.swing.JTextField tfInput1_3;
    private javax.swing.JTextField tfInput1_4;
    private javax.swing.JPasswordField tfInput1_5;
    private javax.swing.JTextField tfInput2_1;
    private javax.swing.JTextField tfInput2_2;
    private javax.swing.JTextField tfInput2_3;
    private javax.swing.JTextField tfInput2_4;
    private javax.swing.JPasswordField tfInput2_5;
    // End of variables declaration//GEN-END:variables
}
