/*
 * Copyright (c) 2017 ARWANTECH CREATIVE TEAM
 *
 * Anda diperkenankan mengedit isi dari source code ini
 * asalkan tetap menyertakan copyright ini.
 *
 * File ini dibuat menggunakan :
 * Editor     : NetBeans IDE 8.0.2
 * NoteBook   : ASUS Notebook K42F
 * OS         : Windows 10 Pro 64bit
 * Compiler   : JDK 8 update 18
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 *      http://www.apache.org/licenses/LICENSE-2.0
 */
package com.arwantech.docjavaui.form;

import com.arwantech.javaui.efek.SlidingForm;
import com.arwantech.javaui.efek.TransitionTextfield;
import com.arwantech.javaui.utils.Utility;
import javax.swing.text.JTextComponent;

/**
 *
 * @author AriMaulana99
 */
public class FormDialog extends javax.swing.JDialog {

    private AppMainFrm main = null;
    private FormDialogPanel panel = null;

    public AppMainFrm getMain() {
        return main;
    }

    public void setMain(AppMainFrm main) {
        this.main = main;
    }

    public FormDialogPanel getPanel() {
        return panel;
    }

    public void setPanel(FormDialogPanel panel) {
        this.panel = panel;
    }
    
    
    
    
    
    /**
     * Creates new form FormDialog
     * @param parent
     * @param modal
     */
    public FormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initUI();
        slidingTopBootomTop();
    }
    
    private void initUI() {
        setInputUI(tfId);
        Utility.setInputUI(tfId, lblInput2_1);
        setInputUI(tfName);
        Utility.setInputUI(tfName, lblInput2_2);
        setInputUI(tfAddress);
        Utility.setInputUI(tfAddress, lblInput2_4);
    }
    
    private void setInputUI(JTextComponent textField) {
        TransitionTextfield tt = new TransitionTextfield(textField);
        tt.setColorType(3);
        tt.setSpeed(50);
        tt.initTransitionKotak();
    }
    
    private void setDataPerson() {
        this.dispose();
        panel.getLblId().setText(tfId.getText());
        panel.getLblName().setText(tfName.getText());
        panel.getLblAge().setText(String.valueOf(jsAge.getValue()));
        panel.getLblAddress().setText(tfAddress.getText());
        
    }
    
    private void slidingTopBootomTop() {
        SlidingForm slidingForm = new SlidingForm(this);
        slidingForm.setWidth(this.getWidth());
        slidingForm.setHeight(this.getHeight());
        slidingForm.setX(350);
        slidingForm.setyFirst(180);
        slidingForm.setyRectangle(260);
        slidingForm.setSpeed(15);
        slidingForm.initSlidingTopBootomTop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblInput2_1 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        lblInput2_2 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lblInput2_4 = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jsAge = new javax.swing.JSpinner();
        lblInput2_6 = new javax.swing.JLabel();
        lblInput2_7 = new javax.swing.JLabel();
        lblInput2_8 = new javax.swing.JLabel();
        lblInput2_9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("x");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Form Dialog");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInput2_1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_1.setForeground(new java.awt.Color(153, 153, 153));
        lblInput2_1.setText("Masukan Input1");
        lblInput2_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 150, 20));

        tfId.setBackground(new java.awt.Color(255, 255, 255));
        tfId.setForeground(new java.awt.Color(102, 102, 102));
        tfId.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(191, 191, 191)));
        tfId.setMinimumSize(new java.awt.Dimension(2, 30));
        tfId.setOpaque(false);
        tfId.setPreferredSize(new java.awt.Dimension(80, 30));
        tfId.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfIdCaretUpdate(evt);
            }
        });
        jPanel2.add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 430, 40));

        lblInput2_2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_2.setForeground(new java.awt.Color(153, 153, 153));
        lblInput2_2.setText("Masukan Input2");
        lblInput2_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 150, 20));

        tfName.setBackground(new java.awt.Color(255, 255, 255));
        tfName.setForeground(new java.awt.Color(102, 102, 102));
        tfName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(191, 191, 191)));
        tfName.setMinimumSize(new java.awt.Dimension(2, 30));
        tfName.setOpaque(false);
        tfName.setPreferredSize(new java.awt.Dimension(80, 30));
        tfName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfNameCaretUpdate(evt);
            }
        });
        jPanel2.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 430, 40));

        lblInput2_4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_4.setForeground(new java.awt.Color(153, 153, 153));
        lblInput2_4.setText("Masukan Input4");
        lblInput2_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 150, 20));

        tfAddress.setBackground(new java.awt.Color(255, 255, 255));
        tfAddress.setForeground(new java.awt.Color(102, 102, 102));
        tfAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(191, 191, 191)));
        tfAddress.setMinimumSize(new java.awt.Dimension(2, 30));
        tfAddress.setOpaque(false);
        tfAddress.setPreferredSize(new java.awt.Dimension(80, 30));
        tfAddress.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfAddressCaretUpdate(evt);
            }
        });
        jPanel2.add(tfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 430, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Reset Input");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(77, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 100, -1));

        jsAge.setPreferredSize(new java.awt.Dimension(37, 35));
        jPanel2.add(jsAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 430, -1));

        lblInput2_6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_6.setForeground(new java.awt.Color(51, 51, 51));
        lblInput2_6.setText("Age Person");
        lblInput2_6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 70, 30));

        lblInput2_7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_7.setForeground(new java.awt.Color(51, 51, 51));
        lblInput2_7.setText("Address");
        lblInput2_7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 50, 20));

        lblInput2_8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_8.setForeground(new java.awt.Color(51, 51, 51));
        lblInput2_8.setText("Name Person");
        lblInput2_8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, 20));

        lblInput2_9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_9.setForeground(new java.awt.Color(51, 51, 51));
        lblInput2_9.setText("ID Person");
        lblInput2_9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 60, 20));

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Kirim Data");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPreferredSize(new java.awt.Dimension(77, 35));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 110, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tfIdCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfIdCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdCaretUpdate

    private void tfNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfNameCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameCaretUpdate

    private void tfAddressCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfAddressCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddressCaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Utility.resetInput(tfId, tfName, jsAge, tfAddress);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setDataPerson();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormDialog dialog = new FormDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jsAge;
    private javax.swing.JLabel lblInput2_1;
    private javax.swing.JLabel lblInput2_2;
    private javax.swing.JLabel lblInput2_4;
    private javax.swing.JLabel lblInput2_6;
    private javax.swing.JLabel lblInput2_7;
    private javax.swing.JLabel lblInput2_8;
    private javax.swing.JLabel lblInput2_9;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
