/*
 * Copyright (c) 2017 ARWANTECH CREATIVE TEAM
 *
 * Anda diperkenankan mengedit isi dari source code ini
 * asalkan tetap menyertakan copyright ini.
 *
 * File ini dibuat menggunakan :
 * Editor     : NetBeans IDE 8.0.2
 * NoteBook   : ASUS Notebook K42F
 * OS         : Windows 10 Pro 64bit
 * Compiler   : JDK 8 update 18
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 *      http://www.apache.org/licenses/LICENSE-2.0
 */
package com.arwantech.docjavaui.form;

import com.arwantech.javaui.efek.TransitionTextfield;
import com.arwantech.javaui.utils.Utility;
import javax.swing.JComponent;
import javax.swing.text.JTextComponent;

/**
 *
 * @author AriMaulana99
 */
public class FormValidasi extends javax.swing.JPanel {
    private AppMainFrm main = null;

    public AppMainFrm getMain() {
        return main;
    }

    public void setMain(AppMainFrm main) {
        this.main = main;
    }
    
    
    /**
     * Creates new form DataTables
     */
    public FormValidasi() {
        initComponents();
        initUI();
    }
    
    private void initUI() {
        setInputUI(tfInput2_1);
        Utility.setInputUI(tfInput2_1, lblInput2_1);
        setInputUI(tfInput2_5);
        Utility.setInputUI(tfInput2_5, lblInput2_5);
    }

    private void setInputUI(JTextComponent textField) {
        TransitionTextfield tt = new TransitionTextfield(textField);
        tt.setColorType(3);
        tt.setSpeed(50);
        tt.initTransitionKotak();
    }
    
    private boolean validasi() {
        JComponent component[] = { tfInput2_1, tfInput2_5, cbxLimitData, jSpinner1, Utility.groupRbt(buttonGroup1), Utility.groupCbx(buttonGroup2) };
        String inputName[] = {"TEXTFIELD", "PASSWORD FIELD", "COMBO BOX", "SPINER", "RADIO BUTTON", "CHECKBOX"};
        boolean validasi = Utility.validasiInputNotNull(component, inputName);
        return validasi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblInput2_1 = new javax.swing.JLabel();
        tfInput2_1 = new javax.swing.JTextField();
        lblInput2_5 = new javax.swing.JLabel();
        tfInput2_5 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbxLimitData = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jRadioButton1 = new javax.swing.JRadioButton();
        lblInput2_6 = new javax.swing.JLabel();
        lblInput2_7 = new javax.swing.JLabel();
        lblInput2_8 = new javax.swing.JLabel();
        lblInput2_9 = new javax.swing.JLabel();
        lblInput2_10 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        lblInput2_11 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 191, 191), 1, true));

        jPanel12.setBackground(new java.awt.Color(56, 59, 68));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Form Validasi");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addContainerGap(917, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 191, 191), 1, true));

        jPanel16.setBackground(new java.awt.Color(242, 242, 242));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Input Validasi");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInput2_1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_1.setForeground(new java.awt.Color(153, 153, 153));
        lblInput2_1.setText("Masukan Input1");
        lblInput2_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 180, 20));

        tfInput2_1.setBackground(new java.awt.Color(255, 255, 255));
        tfInput2_1.setForeground(new java.awt.Color(102, 102, 102));
        tfInput2_1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(191, 191, 191)));
        tfInput2_1.setMinimumSize(new java.awt.Dimension(2, 30));
        tfInput2_1.setOpaque(false);
        tfInput2_1.setPreferredSize(new java.awt.Dimension(80, 30));
        tfInput2_1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfInput2_1CaretUpdate(evt);
            }
        });
        jPanel2.add(tfInput2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 430, 40));

        lblInput2_5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_5.setForeground(new java.awt.Color(153, 153, 153));
        lblInput2_5.setText("Masukan Input2");
        lblInput2_5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 180, 20));

        tfInput2_5.setBackground(new java.awt.Color(255, 255, 255));
        tfInput2_5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(191, 191, 191)));
        jPanel2.add(tfInput2_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 430, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Reset Input");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(77, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 100, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Check Validasi");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(77, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 130, -1));

        cbxLimitData.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- pilih item --", "item1", "item2", "item3", "item4", "item5" }));
        cbxLimitData.setOpaque(false);
        cbxLimitData.setPreferredSize(new java.awt.Dimension(65, 35));
        cbxLimitData.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLimitDataItemStateChanged(evt);
            }
        });
        jPanel2.add(cbxLimitData, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 430, -1));

        jSpinner1.setMinimumSize(new java.awt.Dimension(37, 30));
        jSpinner1.setPreferredSize(new java.awt.Dimension(37, 35));
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 430, -1));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton1.setText("jRadioButton3");
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, 20));

        lblInput2_6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblInput2_6.setForeground(new java.awt.Color(51, 51, 51));
        lblInput2_6.setText("Input JComboBox");
        lblInput2_6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 30));

        lblInput2_7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblInput2_7.setForeground(new java.awt.Color(51, 51, 51));
        lblInput2_7.setText("Input JTextField");
        lblInput2_7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, 20));

        lblInput2_8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblInput2_8.setForeground(new java.awt.Color(51, 51, 51));
        lblInput2_8.setText("Input JSpiner");
        lblInput2_8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 80, 30));

        lblInput2_9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblInput2_9.setForeground(new java.awt.Color(51, 51, 51));
        lblInput2_9.setText("Input JCheckBox");
        lblInput2_9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 100, 20));

        lblInput2_10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblInput2_10.setForeground(new java.awt.Color(51, 51, 51));
        lblInput2_10.setText("Input JPasswordField");
        lblInput2_10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, 20));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton2.setText("jRadioButton1");
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, 20));

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton3.setText("jRadioButton2");
        jPanel2.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, 20));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jCheckBox1);
        jCheckBox1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBox1.setText("jCheckBox2");
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, 20));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jCheckBox2);
        jCheckBox2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBox2.setText("jCheckBox1");
        jPanel2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, 20));

        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 630, 10));

        lblInput2_11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblInput2_11.setForeground(new java.awt.Color(51, 51, 51));
        lblInput2_11.setText("Input JRadioButton");
        lblInput2_11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblInput2_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 110, 20));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        add(jPanel11, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tfInput2_1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfInput2_1CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInput2_1CaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Utility.resetInput(tfInput2_1, tfInput2_5, cbxLimitData, jSpinner1, jRadioButton1, 
                jRadioButton2, jRadioButton3, jCheckBox1, jCheckBox2);
        Utility.resetButtonGroup(buttonGroup1, buttonGroup2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (validasi() == true) {
            Utility.messageBox(main, jButton1, "Transaksi berhasil dilakukan");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbxLimitDataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLimitDataItemStateChanged

    }//GEN-LAST:event_cbxLimitDataItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbxLimitData;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblInput2_1;
    private javax.swing.JLabel lblInput2_10;
    private javax.swing.JLabel lblInput2_11;
    private javax.swing.JLabel lblInput2_5;
    private javax.swing.JLabel lblInput2_6;
    private javax.swing.JLabel lblInput2_7;
    private javax.swing.JLabel lblInput2_8;
    private javax.swing.JLabel lblInput2_9;
    private javax.swing.JTextField tfInput2_1;
    private javax.swing.JPasswordField tfInput2_5;
    // End of variables declaration//GEN-END:variables
}
