/*
 * Copyright (c) 2017 ARWANTECH CREATIVE TEAM
 *
 * Anda diperkenankan mengedit isi dari source code ini
 * asalkan tetap menyertakan copyright ini.
 *
 * File ini dibuat menggunakan :
 * Editor     : NetBeans IDE 8.0.2
 * NoteBook   : ASUS Notebook K42F
 * OS         : Windows 10 Pro 64bit
 * Compiler   : JDK 8 update 18
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 *      http://www.apache.org/licenses/LICENSE-2.0
 */
package com.arwantech.docjavaui.form;

import com.arwantech.docjavaui.domain.User;
import com.arwantech.docjavaui.enums.Images;
import com.arwantech.docjavaui.repository.UserRepository;
import com.arwantech.javaui.efek.TransitionTextfield;
import com.arwantech.javaui.utils.Utility;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.text.JTextComponent;

/**
 *
 * @author AriMaulana99
 */
public class LoginFrm extends javax.swing.JFrame {
    
    /**
     * Creates new form LoginFrm
     */
    public LoginFrm() {
        initComponents();
        initUI();
    }
    
    private void initUI() {
        this.setResizable(false);
        Utility.onEnter(tfUsername, tfPassowrd);
        
        lblLogo.setIcon(new ImageIcon(Images.ICON_LOGO_ARWANTECH.getScaledInstance(300, 60, 45)));
        btnLogin.setIcon(new ImageIcon(Images.ICON_LOGIN.getScaledInstance(20, 20, 20)));
        
        setInputUI1(tfUsername);
        Utility.setInputUI(tfUsername, lblInput2_1);
        setInputUI1(tfPassowrd);
        Utility.setInputUI(tfPassowrd, lblInput2_5);
    }
    
    private void setInputUI1(JTextComponent textField) {
        TransitionTextfield tt = new TransitionTextfield(textField);
        tt.setColorType(3);
        tt.setSpeed(50);
        tt.initTransitionKotak();
    }
    
    private void login() { 
        try {
            String username = tfUsername.getText();
            String password = tfPassowrd.getText();
            UserRepository userRepository = new UserRepository();
            User user = userRepository.getByUsernameAndPassword(username, password);
            if (validasi()) {
                if (user != null) {
                    this.dispose();
                    new AppMainFrm(user).setVisible(true);
                } else {
                    Utility.messageInformation(null, "Username dan password salah !");
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private boolean validasi() {
        JComponent component[] = {tfUsername, tfPassowrd};
        String inputName[] = {"USERNAME", "PASSWORD"};
        boolean validasi = Utility.validasiInputNotNull(component, inputName);
        return validasi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblInput2_1 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        lblInput2_5 = new javax.swing.JLabel();
        tfPassowrd = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblInput2_3 = new javax.swing.JLabel();
        lblInput2_4 = new javax.swing.JLabel();
        lblInput2_2 = new javax.swing.JLabel();
        lblInput2_6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 172, 145));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(410, 120));

        lblLogo.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(410, 330));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInput2_1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_1.setForeground(new java.awt.Color(153, 153, 153));
        lblInput2_1.setText("Masukan Username");
        lblInput2_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(lblInput2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 170, 20));

        tfUsername.setBackground(new java.awt.Color(255, 255, 255));
        tfUsername.setForeground(new java.awt.Color(102, 102, 102));
        tfUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(191, 191, 191)));
        tfUsername.setMinimumSize(new java.awt.Dimension(2, 30));
        tfUsername.setOpaque(false);
        tfUsername.setPreferredSize(new java.awt.Dimension(80, 30));
        tfUsername.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfUsernameCaretUpdate(evt);
            }
        });
        jPanel3.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 320, 40));

        lblInput2_5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInput2_5.setForeground(new java.awt.Color(153, 153, 153));
        lblInput2_5.setText("Masukan Password");
        lblInput2_5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(lblInput2_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 190, 20));

        tfPassowrd.setBackground(new java.awt.Color(255, 255, 255));
        tfPassowrd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(191, 191, 191)));
        tfPassowrd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPassowrdKeyPressed(evt);
            }
        });
        jPanel3.add(tfPassowrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 320, 40));

        btnLogin.setBackground(new java.awt.Color(0, 102, 204));
        btnLogin.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setPreferredSize(new java.awt.Dimension(77, 37));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 187, 320, 40));

        lblInput2_3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblInput2_3.setForeground(new java.awt.Color(27, 172, 145));
        lblInput2_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInput2_3.setText("Arwantech Documentation Custom JavaUI");
        lblInput2_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(lblInput2_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 30));

        lblInput2_4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblInput2_4.setForeground(new java.awt.Color(27, 172, 145));
        lblInput2_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInput2_4.setText("Version 1.0");
        lblInput2_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(lblInput2_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 410, 20));

        lblInput2_2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblInput2_2.setForeground(new java.awt.Color(27, 172, 145));
        lblInput2_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInput2_2.setText("Copyright (c) 2017 ARWANTECH CREATIVE TEAM");
        lblInput2_2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        lblInput2_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblInput2_6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblInput2_6.setForeground(new java.awt.Color(27, 172, 145));
        lblInput2_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInput2_6.setText("user : ari   pass : 12345678");
        lblInput2_6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInput2_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblInput2_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lblInput2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInput2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsernameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfUsernameCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameCaretUpdate

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void tfPassowrdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPassowrdKeyPressed
        if (evt.getKeyCode() == 10) {
            login();
        }
    }//GEN-LAST:event_tfPassowrdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblInput2_1;
    private javax.swing.JLabel lblInput2_2;
    private javax.swing.JLabel lblInput2_3;
    private javax.swing.JLabel lblInput2_4;
    private javax.swing.JLabel lblInput2_5;
    private javax.swing.JLabel lblInput2_6;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPasswordField tfPassowrd;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
